<?php

/**
 * BaseCustomer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $customer_name
 * @property string $customer_type
 * @property string $location
 * @property string $contact_addr
 * @property string $email
 * @property string $phone_number
 * @property PurchaseOrder $Orders
 * 
 * @method string        getCustomerName()  Returns the current record's "customer_name" value
 * @method string        getCustomerType()  Returns the current record's "customer_type" value
 * @method string        getLocation()      Returns the current record's "location" value
 * @method string        getContactAddr()   Returns the current record's "contact_addr" value
 * @method string        getEmail()         Returns the current record's "email" value
 * @method string        getPhoneNumber()   Returns the current record's "phone_number" value
 * @method PurchaseOrder getOrders()        Returns the current record's "Orders" value
 * @method Customer      setCustomerName()  Sets the current record's "customer_name" value
 * @method Customer      setCustomerType()  Sets the current record's "customer_type" value
 * @method Customer      setLocation()      Sets the current record's "location" value
 * @method Customer      setContactAddr()   Sets the current record's "contact_addr" value
 * @method Customer      setEmail()         Sets the current record's "email" value
 * @method Customer      setPhoneNumber()   Sets the current record's "phone_number" value
 * @method Customer      setOrders()        Sets the current record's "Orders" value
 * 
 * @package    products
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCustomer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customer');
        $this->hasColumn('customer_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('customer_type', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('contact_addr', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('phone_number', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PurchaseOrder as Orders', array(
             'local' => 'id',
             'foreign' => 'customer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}