<?php

/**
 * BasePurchaseOrder
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $customer_id
 * @property Product $Product
 * @property Customer $Customer
 * 
 * @method integer       getProductId()   Returns the current record's "product_id" value
 * @method integer       getCustomerId()  Returns the current record's "customer_id" value
 * @method Product       getProduct()     Returns the current record's "Product" value
 * @method Customer      getCustomer()    Returns the current record's "Customer" value
 * @method PurchaseOrder setProductId()   Sets the current record's "product_id" value
 * @method PurchaseOrder setCustomerId()  Sets the current record's "customer_id" value
 * @method PurchaseOrder setProduct()     Sets the current record's "Product" value
 * @method PurchaseOrder setCustomer()    Sets the current record's "Customer" value
 * 
 * @package    products
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePurchaseOrder extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('purchase_order');
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('customer_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Customer', array(
             'local' => 'customer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}