<?php

/**
 * Baseorders
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $customer_id
 * @property Product $Product
 * @property Doctrine_Collection $Customers
 * 
 * @method integer             getProductId()   Returns the current record's "product_id" value
 * @method integer             getCustomerId()  Returns the current record's "customer_id" value
 * @method Product             getProduct()     Returns the current record's "Product" value
 * @method Doctrine_Collection getCustomers()   Returns the current record's "Customers" collection
 * @method orders              setProductId()   Sets the current record's "product_id" value
 * @method orders              setCustomerId()  Sets the current record's "customer_id" value
 * @method orders              setProduct()     Sets the current record's "Product" value
 * @method orders              setCustomers()   Sets the current record's "Customers" collection
 * 
 * @package    products
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class Baseorders extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('orders');
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('customer_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Customers', array(
             'local' => 'customer_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}