<?php

/**
 * BaseProductCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $category_name
 * @property Doctrine_Collection $Product
 * 
 * @method string              getCategoryName()  Returns the current record's "category_name" value
 * @method Doctrine_Collection getProduct()       Returns the current record's "Product" collection
 * @method ProductCategory     setCategoryName()  Sets the current record's "category_name" value
 * @method ProductCategory     setProduct()       Sets the current record's "Product" collection
 * 
 * @package    products
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProductCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_category');
        $this->hasColumn('category_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}