<?php

/**
 * BaseCustomers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $customer_name
 * @property string $customer_type
 * @property string $location
 * @property string $contact_addr
 * @property string $email
 * @property string $phone_number
 * @property orders $orders2
 * 
 * @method string    getCustomerName()  Returns the current record's "customer_name" value
 * @method string    getCustomerType()  Returns the current record's "customer_type" value
 * @method string    getLocation()      Returns the current record's "location" value
 * @method string    getContactAddr()   Returns the current record's "contact_addr" value
 * @method string    getEmail()         Returns the current record's "email" value
 * @method string    getPhoneNumber()   Returns the current record's "phone_number" value
 * @method orders    getOrders2()       Returns the current record's "orders2" value
 * @method Customers setCustomerName()  Sets the current record's "customer_name" value
 * @method Customers setCustomerType()  Sets the current record's "customer_type" value
 * @method Customers setLocation()      Sets the current record's "location" value
 * @method Customers setContactAddr()   Sets the current record's "contact_addr" value
 * @method Customers setEmail()         Sets the current record's "email" value
 * @method Customers setPhoneNumber()   Sets the current record's "phone_number" value
 * @method Customers setOrders2()       Sets the current record's "orders2" value
 * 
 * @package    products
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCustomers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('customers');
        $this->hasColumn('customer_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('customer_type', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('contact_addr', 'string', 4000, array(
             'type' => 'string',
             'length' => '4000',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => '255',
             ));
        $this->hasColumn('phone_number', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('orders as orders2', array(
             'local' => 'id',
             'foreign' => 'customer_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}