generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Product
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          product
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [id,product_name,product_key,unit_price,description]
        batch_actions: []
#        actions: []
#        object_actions:
#          users: ~
#          _edit:      ~
#          _delete:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
