<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/07 09:44:32

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=products',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
