<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/03/06 17:24:24

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=products',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
