<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/07 09:44:32
sfConfig::add(array(
  'mod_purchase_orders_enabled' => true,
  'mod_purchase_orders_view_class' => 'sfPHP',
));
