<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/06 17:32:42
sfConfig::add(array(
  'mod_purchase_orders_enabled' => true,
  'mod_purchase_orders_view_class' => 'sfPHP',
));
