<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/03/07 09:47:17
sfConfig::add(array(
  'mod_product_category_enabled' => true,
  'mod_product_category_view_class' => 'sfPHP',
));
